[package]
name = "kenken"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/kakacka/kenken"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
